#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    MutableDecl,
    ConstantDecl,
    FunctionDef,
    Conditional,
    Underscore,
    Void,
    Float(f64),
    Backtick,
    InterpolationStart,
    InterpolationEnd,
    Array,
    Object,
    Else,
    Import,
    This,
    Timer,
    Sqrt,
    End,
    Comment(String),
    Max,
    Min,
    Trim,
    Mod,
    Len,
    StrUpper,
    StrLower,
    StrReverse,
    LastWord,
    Sum,
    Drop,
    Zig,
    Match, // uyğun
    Arrow, // ->
    Loop,
    Break,
    Print,
    ConvertString,
    Allocator,
    Continue,
    Round,
    Floor,
    Ceil,
    Newline,
    Method,
    True,
    False,
    Enum,
    Identifier(String),
    Number(i64),
    Indent,
    Dedent,
    ElseIf,
    StringLiteral(String),
    Operator(String), /* TODO: Burası char olmalı */
    LParen,
    Dot,
    RParen,
    LBrace,
    RBrace,
    In,
    Semicolon,
    Colon,
    Comma,
    ListStart,
    ListEnd,
    Return,
    Eof,
    And,       // və
    Or,        // və ya
    DoubleAnd, // &&
    DoubleOr,  // ||
    NumberFn,
    RangeFn,
    Input,
    IntegerType,
    NaturalType,
    StringType,
    ZigConstString,
    ZigConstArray,
    ZigArray,
    ZigNatural,
    ZigInteger,
    Type,
    ZigString,
    CharType,
    BoolType,
    FloatType,
    ZigFloat,
    BigIntegerType,
    LowIntegerType,
}
