use crate::tokens::Token;

pub fn tokenize_word(word: &str) -> Token {
    match word {
        "while" => Token::While,
        "var" => Token::MutableDecl,
        "const" => Token::ConstantDecl,
        "if" => Token::Conditional,
        "elif" => Token::ElseIf,
        "else" => Token::Else,
        "func" => Token::FunctionDef,
        "callable" => Token::FnType,
        "list" => Token::Array,
        "object" => Token::Object,
        "self" => Token::This,
        "match" => Token::Match,
        "break" => Token::Break,
        "continue" => Token::Continue,
        "loop" => Token::Loop,
        "end" => Token::End,
        "return" => Token::Return,
        "drop" => Token::Drop,
        "true" => Token::True,
        "false" => Token::False,
        "in" => Token::In,
        "and" => Token::And,
        "or" => Token::Or,
        "int" => Token::IntegerType,
        "any" => Token::AnyType,
        "str" => Token::StringType,
        "natural" => Token::NaturalType,
        "char" => Token::CharType,
        "bigint" => Token::BigIntegerType,
        "tinyint" => Token::LowIntegerType,
        "float" => Token::FloatType,
        "bool" => Token::BoolType,
        "void" => Token::Void,
        "enum" => Token::Enum,
        "method" => Token::Method,
        "import" => Token::Import,
        "type" => Token::Type,
        other => Token::Identifier(other.to_string()),
    }
}
