use crate::parser::ast::Type;

#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    MutableDecl,
    ConstantDecl,
    FunctionDef,
    Conditional,
    Backtick,
    InterpolationStart,
    TemplatePart(String),
    SiyahiKeyword,
    Object,
    Else,
    End,
    Drop,
    TypeName(Type),
    Loop,
    Break,
    Continue,
    Newline,
    Whitespace,
    BigInteger,
    LowInteger,
    Integer,
    True,
    False,
    String,
    Identifier(String),
    Number(i64),
    Indent,
    Dedent,
    ElseIf,
    StringLiteral(String),
    Operator(String),
    LParen,
    Dot,
    RParen,
    LBrace,
    RBrace,
    In,
    Semicolon,
    Colon,
    Comma,
    ListStart,
    ListEnd,
    Return,
    EOF,
    And,       // və
    Or,        // və ya
    DoubleAnd, // &&
    DoubleOr,  // ||
}
