use std::fmt;

use crate::{lexer::Token, parser::ast::BuiltInFunction};

pub fn tokenize_word(word: &str) -> Token {
    match word.parse::<i64>() {
        Ok(n) => Token::Number(n),
        Err(_) => match word {
            "dəyişən" => Token::MutableDecl,
            "sabit" => Token::ConstantDecl,
            "əgər" => Token::Conditional,
            "yoxsa" => Token::ElseIf,
            "əks" => Token::Else,
            "funksiya" => Token::FunctionDef,
            "siyahı" => Token::Array,
            "Obyekt" => Token::Object,
            "öz" => Token::This,
            "uyğun" => Token::Match,
            "dayan" => Token::Break,
            "davam" => Token::Continue,

            "gəz" => Token::Loop,
            "son" => Token::End,
            "->" => Token::Arrow,
            "qaytar" => Token::Return,
            "çıx" => Token::Drop,
            "doğru" => Token::True,
            "yanlış" => Token::False,
            "içində" => Token::In,
            "və" => Token::And,
            "və_ya" => Token::Or,
            "&&" => Token::DoubleAnd,
            "||" => Token::DoubleOr,
            "ədəd" => Token::NaturalType,
            "tam" => Token::IntegerType,
            "yazı" => Token::StringType,
            "zigsabityazı" => Token::ZigConstString,
            "zigyazı" => Token::ZigString,
            "zigsabitsiyahı" => Token::ZigConstArray,
            "zigsiyahı" => Token::ZigArray,
            "işarə" => Token::CharType,
            "böyük_ədəd" => Token::BigIntegerType,
            "kiçik_ədəd" => Token::LowIntegerType,
            "kəsr" => Token::FloatType,
            "qərar" => Token::BoolType,
            "Çap" => Token::Print,
            "Giriş" => Token::Input,
            "Maksimum" => Token::Max,
            "Minimum" => Token::Min,
            "YazıBöyüt" => Token::StrUpper,
            "VaxtAl" => Token::Timer,
            "Modul" => Token::Mod,
            "ƏdədəÇevir" => Token::NumberFn,
            "Cəm" => Token::Sum,
            "Yuvarlaqlaşdır" => Token::Round,
            "AşağıYuvarlaqlaşdır" => Token::Floor,
            "YuxarıYuvarlaqlaşdır" => Token::Ceil,
            "Uzunluq" => Token::Len,
            "Sonsöz" => Token::LastWord,
            "YazıTərs" => Token::StrReverse,
            "YazıyaÇevir" => Token::ConvertString,
            "Kök" => Token::Sqrt,
            "aralıq" => Token::RangeFn,
            "növ" => Token::Enum,
            "metod" => Token::Method,
            "Zig" => Token::Zig,
            "ƏlavəEt" => Token::Import,
            "tip" => Token::Type,
            "YaddaşAl" => Token::Allocator,
            "YazıKiçilt" => Token::StrLower,
            other => Token::Identifier(other.to_string()),
        },
    }
}

impl fmt::Display for BuiltInFunction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            BuiltInFunction::StrReverse => "YazıTərs",
            BuiltInFunction::Print => "Çap",
            BuiltInFunction::Len => "Uzunluq",
            BuiltInFunction::Range => "Aralıq",
            BuiltInFunction::Timer => "Timer",
            BuiltInFunction::Input => "Giriş",
            BuiltInFunction::Sum => "Cəm",
            BuiltInFunction::Sqrt => "Kvadrat kök",
            BuiltInFunction::Round => "Yuvarlama",
            BuiltInFunction::StrUpper => "YazıBöyüt",
            BuiltInFunction::Floor => "Yuvarlama",
            BuiltInFunction::Ceil => "Yuvarlama",
            BuiltInFunction::Mod => "Modul",
            BuiltInFunction::Max => "Maksimum",
            BuiltInFunction::Min => "Minimum",
            BuiltInFunction::Number => "ƏdədəÇevir",
            BuiltInFunction::LastWord => "Sonsöz",
            BuiltInFunction::Zig => "Zig",
            BuiltInFunction::Allocator => "YaddaşAl",
            BuiltInFunction::StrLower => "YazıKiçilt",
            BuiltInFunction::ConvertString => "YazıyaÇevir",
        };
        write!(f, "{name}")
    }
}
