name: AzLang Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run parser tests
        run: cargo test --package parser --verbose

      - name: Run validator tests
        run: cargo test --package validator --verbose

      - name: Run transpiler tests
        run: cargo test --package transpiler --verbose

      - name: Run compiler tests
        run: cargo test --package compiler --verbose
